import JSZip from 'jszip';
import { CAMProject, ToolpathOperation, ExportSettings, ToolDefinition } from '../types';

export interface ExportResult {
  combinedSvg?: string;
  filesByTool?: { fileName: string; content: string; toolName: string }[];
  zipBlob?: Blob;
  jobSheet: string;
}

export async function exportToolpathSVGs(project: CAMProject): Promise<ExportResult> {
  const { operations, width, height, units, exportSettings, tools, fileName } = project;
  const baseName = (fileName.replace(/\.svg$/i, '') || 'shaper_project') + '_' + (exportSettings.prefix || 'toolpath');

  const strokeWidthStr = units === 'inch' ? '0.010in' : '0.254mm';
  const unitSuffix = units === 'inch' ? 'in' : 'mm';

  // 1. Generate Combined SVG
  const combinedSvg = generateSvgContent(
    operations,
    width,
    height,
    units,
    strokeWidthStr,
    unitSuffix,
    exportSettings,
    'All Tools Combined'
  );

  // 2. Generate Multi-file SVGs by Tool
  const opsByTool = new Map<string, ToolpathOperation[]>();
  for (const op of operations) {
    if (!op.visible) continue;
    const list = opsByTool.get(op.toolId) || [];
    list.push(op);
    opsByTool.set(op.toolId, list);
  }

  const filesByTool: { fileName: string; content: string; toolName: string }[] = [];
  for (const [toolId, toolOps] of opsByTool.entries()) {
    const tool = toolOps[0].tool;
    const cleanToolName = tool.name.replace(/[^a-zA-Z0-9_-]/g, '_');
    const toolSvg = generateSvgContent(
      toolOps,
      width,
      height,
      units,
      strokeWidthStr,
      unitSuffix,
      exportSettings,
      `Tool: ${tool.name}`
    );
    const subFileName = `${baseName}_${cleanToolName}.svg`;
    filesByTool.push({
      fileName: subFileName,
      content: toolSvg,
      toolName: tool.name,
    });
  }

  // 3. Generate Job Sheet Markdown
  const jobSheet = generateJobSheet(project, filesByTool);

  // 4. If format is 'both' or 'multiple', create ZIP package
  let zipBlob: Blob | undefined;
  if (exportSettings.format === 'both' || exportSettings.format === 'multiple') {
    const zip = new JSZip();

    if (exportSettings.format === 'both') {
      zip.file(`${baseName}_combined.svg`, combinedSvg);
    }

    for (const file of filesByTool) {
      zip.file(file.fileName, file.content);
    }

    zip.file(`${baseName}_CUT_GUIDE.md`, jobSheet);
    zipBlob = await zip.generateAsync({ type: 'blob' });
  }

  return {
    combinedSvg,
    filesByTool,
    zipBlob,
    jobSheet,
  };
}

function generateSvgContent(
  ops: ToolpathOperation[],
  width: number,
  height: number,
  units: string,
  strokeWidth: string,
  unitSuffix: string,
  settings: ExportSettings,
  groupLabel: string
): string {
  let svgPathsXml = '';

  for (const op of ops) {
    if (!op.visible) continue;

    const color = settings.colorCodeByBit ? op.color : '#000000';
    const depthStr = `${op.currentPassDepth.toFixed(3)}${unitSuffix}`;

    svgPathsXml += `  <!-- Operation: ${op.name} | Tool: ${op.tool.name} | Target Depth: ${depthStr} -->\n`;
    svgPathsXml += `  <g id="${escapeXml(op.id)}" shaper:cutDepth="${depthStr}" shaper:pathType="online">\n`;

    for (let sIdx = 0; sIdx < op.segments.length; sIdx++) {
      const seg = op.segments[sIdx];
      if (seg.points.length < 2) continue;

      let d = `M ${seg.points[0].x.toFixed(4)} ${seg.points[0].y.toFixed(4)}`;
      for (let pIdx = 1; pIdx < seg.points.length; pIdx++) {
        d += ` L ${seg.points[pIdx].x.toFixed(4)} ${seg.points[pIdx].y.toFixed(4)}`;
      }

      svgPathsXml += `    <path d="${d}" fill="none" stroke="${color}" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" shaper:cutDepth="${depthStr}" shaper:pathType="online" />\n`;
    }

    svgPathsXml += `  </g>\n\n`;
  }

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Shaper Origin Toolpath Generator & Optimizer -->
<svg version="1.1"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns:shaper="http://www.shapertools.com/namespaces/shaper"
     width="${width.toFixed(2)}${unitSuffix}"
     height="${height.toFixed(2)}${unitSuffix}"
     viewBox="0 0 ${width.toFixed(2)} ${height.toFixed(2)}">
  <title>${escapeXml(groupLabel)}</title>
  <desc>Optimized 2.5D 'On-Line' toolpaths with safe volumetric overtravel compensation.</desc>
  
${svgPathsXml}
</svg>`;
}

function generateJobSheet(
  project: CAMProject,
  files: { fileName: string; content: string; toolName: string }[]
): string {
  const { fileName, units, width, height, totalThickness, operations } = project;

  let totalDist = 0;
  let totalTime = 0;
  for (const op of operations) {
    if (op.visible) {
      totalDist += op.estimatedLength;
      totalTime += op.estimatedTimeSec;
    }
  }

  const mins = Math.floor(totalTime / 60);
  const secs = Math.round(totalTime % 60);

  let sheet = `# Shaper Origin Cut Guide: ${fileName}\n\n`;
  sheet += `### Project Overview\n`;
  sheet += `- **Dimensions**: ${width.toFixed(2)} x ${height.toFixed(2)} ${units}\n`;
  sheet += `- **Stock Thickness**: ${totalThickness.toFixed(2)} ${units}\n`;
  sheet += `- **Total Cut Distance**: ${totalDist.toFixed(2)} ${units}\n`;
  sheet += `- **Estimated Machining Time**: ~${mins}m ${secs}s\n\n`;

  sheet += `### Recommended Tool Sequence\n`;
  const toolOps = new Map<string, ToolpathOperation[]>();
  for (const op of operations) {
    if (!op.visible) continue;
    const list = toolOps.get(op.toolId) || [];
    list.push(op);
    toolOps.set(op.toolId, list);
  }

  let step = 1;
  for (const [_, ops] of toolOps.entries()) {
    const tool = ops[0].tool;
    sheet += `#### Step ${step}: Install **${tool.name}** (Ø ${tool.diameter} ${units})\n`;
    sheet += `- **Cut Mode on Origin**: Select **On-Line**\n`;
    sheet += `- **Passes**: ${ops.length} operation(s)\n`;
    for (const op of ops) {
      sheet += `  - ${op.name} (Depth: -${op.currentPassDepth.toFixed(3)} ${units})\n`;
    }
    step++;
    sheet += `\n`;
  }

  sheet += `\n### Included Files\n`;
  for (const f of files) {
    sheet += `- \`${f.fileName}\` (${f.toolName})\n`;
  }

  return sheet;
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
